import streamlit as st
import replicate
import os

# COLOK LANGSUNG - JANGAN PAKE SECRETS DULU
os.environ["REPLICATE_API_TOKEN"] = "r8_TcFLPXOKOGi35bezM4BGlhPBEYO4F971Mn8yi" 
# ^^^^ GANTI ......... DENGAN SISA TOKEN KAMU SAMPE HABIS. 1 BARIS. JANGAN ENTER.
